### ISSUE TITLE
the [get_code] button in aistudio.google.com provide a bad code  about how to use grounding tools

### ISSUE THREAD

**Issue by indeedzcr** [google-gemini/generative-ai-python#650] opened 2024-12-13 07:56 UTC
### Description of the bug:

when I switch the ground button on with  a threshold 0.3, the aistudio.google.com give the code below:
![5876b8932b21596f281a78a27c9b414](https://github.com/user-attachments/assets/5d7e3392-7873-4fbd-b5b4-74cfc18c32b3)

```
"""
Install an additional SDK for JSON schema support Google AI Python SDK

$ pip install google.ai.generativelanguage
"""

import os
import google.generativeai as genai
from google.ai.generativelanguage_v1beta.types import content

genai.configure(api_key=os.environ["GEMINI_API_KEY"])

# Create the model
generation_config = {
  "temperature": 0,
  "top_p": 0.95,
  "top_k": 40,
  "max_output_tokens": 8192,
  "response_mime_type": "text/plain",
}

model = genai.GenerativeModel(
  model_name="gemini-1.5-pro",
  generation_config=generation_config,
  tools = [
    genai.protos.Tool(
      google_search_retrieval = genai.protos.GoogleSearchRetrieval(
        genai.protos.DynamicRetrievalConfig(
          mode = genai.protos.DynamicRetrievalConfig.Mode.MODE_DYNAMIC,
          dynamic_threshold = 0.3,
        ),
      ),
    ),
  ],
)
```

that code  runs ouputs:
```
TypeError                                 Traceback (most recent call last)
[<ipython-input-5-d3c7ebea980b>](https://localhost:8080/#) in <cell line: 17>()
     20   tools = [
     21     genai.protos.Tool(
---> 22       google_search_retrieval = genai.protos.GoogleSearchRetrieval(
     23         genai.protos.DynamicRetrievalConfig(
     24           mode = genai.protos.DynamicRetrievalConfig.Mode.MODE_DYNAMIC,

[/usr/local/lib/python3.10/dist-packages/proto/message.py](https://localhost:8080/#) in __init__(self, mapping, ignore_unknown_fields, **kwargs)
    704         else:
    705             # Sanity check: Did we get something not a map? Error if so.
--> 706             raise TypeError(
    707                 "Invalid constructor input for %s: %r"
    708                 % (

TypeError: Invalid constructor input for GoogleSearchRetrieval: mode: MODE_DYNAMIC
dynamic_threshold: 0.3
```

official code from official page can not run successfully? it is wired!

my package is up to date, and compatitable :
```
!pip install google.ai.generativelanguage==0.6.10
!pip install google-generativeai==0.8.3 
```

### Actual vs expected behavior:

according to the api manual on https://ai.google.dev/gemini-api/docs/grounding?lang=python

the correct use is :
```
import os
import google.generativeai as genai
model = genai.GenerativeModel('models/gemini-1.5-pro-002')
response = model.generate_content(contents="Who won Wimbledon this year?",
                                  tools='google_search_retrieval')
print(response.text)
```

### Any other information you'd like to share?

please fix that bad code provided by aistudio.google.com

**Comment by Gunand3043** [comment] 2024-12-16 05:14
Hey @indeedzcr, Thanks for flagging the issue. The problem is that the GoogleSearchRetrieval class is expecting a named argument `dynamic_retrieval_config`. 

Below is the expected code:

```
model = genai.GenerativeModel(
  model_name="gemini-1.5-pro",
  generation_config=generation_config,
  tools = [
    genai.protos.Tool(
      google_search_retrieval = genai.protos.GoogleSearchRetrieval(
         dynamic_retrieval_config = genai.protos.DynamicRetrievalConfig(
          mode = genai.protos.DynamicRetrievalConfig.Mode.MODE_DYNAMIC,
          dynamic_threshold = 0.3,
        ),
      ),
    ),
  ],
)
```

**Comment by MarkDaoust** [comment] 2024-12-17 14:12
I've submitted an internal fix for this. IDK what the release schedule is, but this should be fixed soon.

**Closed by MarkDaoust** 2024-12-17 14:12 UTC
Labels: type:bug, status:triaged, component:python sdk

**Comment by climate-tech** [comment] 2025-01-20 18:47
+1 for this, can't move forward on Gemini project without it!

Thank you!!
