### ISSUE TITLE
Deploy as conda library

### ISSUE THREAD

**Issue by mikekuzak** [google-gemini/generative-ai-python#97] opened 2023-11-20 15:25 UTC
### Description of the feature request:

Hi 

Any chance of deploying this as a conda library ?

**Comment by MarkDaoust** [comment] 2024-05-17 22:41
@macd - someone else was asking about this, right?

**Comment by MarkDaoust** [comment] 2024-08-27 23:14
Duplicate of: https://github.com/google-gemini/generative-ai-python/issues/320

**Closed by MarkDaoust** 2024-08-27 23:14 UTC
Labels: type:feature request, component:python sdk
