### ISSUE TITLE
Invalid operation: The `response.parts`

### ISSUE THREAD

**Issue by Pratik-Kumar-Cse** [google-gemini/generative-ai-python#526] opened 2024-08-26 12:00 UTC
### Description of the bug:

Invalid operation: The `response.parts` quick accessor requires a single candidate, but none were returned. Please check the `response.prompt_feedback` to determine if the prompt was blocked.

### Actual vs expected behavior:

I am calling the llm using image and video like this 

response = model.generate_content(
        [prompt, video_file],
        request_options={"timeout": 600},
        safety_settings=safety_settings,
    )

**Comment by MarkDaoust** [comment] 2024-08-26 20:06
There are some improved error messages in: https://github.com/google-gemini/generative-ai-python/pull/527

**Comment by MarkDaoust** [comment] 2024-08-26 23:25
Unless there's something new, let's call this a duplicate of #170, with https://github.com/google-gemini/generative-ai-python/pull/527 as a fix.

**Closed** 2024-08-27 00:09 UTC

**Comment by Pratik-Kumar-Cse** [comment] 2024-08-27 04:38
when I try to access the response.text then this error message will come but I am able to access token used
